version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - my-datavolume:/var/lib/mysql
      - ./templates/html.tpl:/templates/html.tpl
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: name_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  php-apache:
    container_name: phpapache-container
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 60:80
    volumes:
      - ./php/:/var/www/html/
      - ./templates/html.tpl:/templates/html.tpl
  
  phpmyadmin:
    image: phpmyadmin
    ports:
        - '6060:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql
    volumes:
      - ./templates/html.tpl:/templates/html.tpl

volumes:
  my-datavolume:
